FROM python:3.10.0-slim-bullseye 

# system dependencies
RUN apt update
RUN apt install -y curl git gcc python3-dev

# python dependencies
COPY . .
RUN pip install --upgrade pip setuptools wheel
RUN poetry install
RUN pip install autopep8