name: Build and publish Docker image

on:
  push:
    paths:
      - '.github/workflows/docker.yml'
    branches:
      - "main"

  workflow_run:
    workflows: ["Test script"]
    branches: [main]
    types: 
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: itsnebulalol
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/permasigner/permasigner:latest
